"""The video agent's generation intelligence — how a customer command becomes
a cinematic reel.

This module is the agent's KNOWLEDGE, not a renderer. It encodes what we learned
from the Higgsfield skill set (higgsfield-generate / product-photoshoot) so the
planner LLM and the provider layer agree on:

  1. which Higgsfield model to use for each job (MODEL_ROUTING / VIDEO_MODELS /
     IMAGE_MODELS),
  2. the controlled vocabulary for cinematic direction (CAMERA_MOVES / LIGHTING /
     LOOK) — so prompts read like a DP's shot list, not amateur text,
  3. what each of the 3 scene roles should look like (SCENE_ROLE_TEMPLATES),
  4. the end-to-end pipeline that turns "make me a video for X" into shots
     (PIPELINE), and
  5. the exact instruction block the planner LLM receives (PLANNER_SYSTEM_PROMPT),
     which makes it emit a structured scene_plan the provider can execute.

DESIGN DECISION (2026-07-22, supersedes the HyperFrames-as-engine draft):
The cinematic footage is generated by **Higgsfield image-to-video** conditioned
on the customer's REAL product photos (crawled from their site). HyperFrames is
demoted to the OVERLAY/branding/stitch layer only — video models render bad text,
so captions, logo, price and the CTA end-card are composited by HyperFrames on
top of the cinematic clips. The quality bar is a realistic, cinematic ad with
professional camera moves — never motion-graphics-over-a-gradient.
"""

from __future__ import annotations

# --------------------------------------------------------------------------- #
# 1. Model routing — distilled from higgsfield-generate/references/model-catalog
# --------------------------------------------------------------------------- #

IMAGE_MODELS: dict[str, dict] = {
    # Brand-quality product stills — the keyframe the video is animated FROM.
    # In production we call `higgsfield product-photoshoot` (backend prompt
    # enhancer) with a mode; via the MCP we use gpt_image_2 with a full prompt.
    "product_photoshoot": {
        "id": "gpt_image_2",
        "use_for": "cinematic product keyframe from the customer's real product photo",
        "modes": [
            "product_shot",       # neutral / studio / catalog background
            "lifestyle_scene",    # product in a real environment, in use
            "closeup_product_with_person",
            "conceptual_product",  # levitating / splash / surreal
        ],
        "takes_reference_image": True,
    },
    "soul_cinema": {
        "id": "soul_cinema",
        "use_for": "cinematic still, film-grade lighting — moody hero frames",
    },
    "soul_location": {
        "id": "soul_location",
        "use_for": "environments / backgrounds with no product or people",
    },
}

VIDEO_MODELS: dict[str, dict] = {
    # DEFAULT cinematic engine: image-to-video, multi-shot, up to 4K.
    "seedance_2_0": {
        "id": "seedance_2_0",
        "use_for": "default serious cinematic image-to-video (4-15s), the reel's scenes",
        "needs_start_image": True,
        "duration_range": (4, 15),
        "max_resolution": "4k",
    },
    # Top film-grade fidelity — reserve for the hero scene when the brief is premium.
    "cinema_studio_video_3_0": {
        "id": "cinema_studio_video_3_0",
        "use_for": "top-tier cinema-grade look, highest fidelity hero shot",
        "needs_start_image": False,
    },
    # Purpose-built ad/UGC pipeline; can import a product straight from a URL.
    "marketing_studio_video": {
        "id": "marketing_studio_video",
        "use_for": "full branded ad / UGC / unboxing / product demo; import-from-URL",
        "imports_product_from_url": True,
    },
    # Cheaper substitute for calm single-plane scenes with little motion.
    "kling_3_0": {
        "id": "kling3_0",
        "use_for": "budget single-plane scene, low motion",
        "needs_start_image": False,
    },
    # Stylized / bold i2v from one required start frame (not the default look).
    "grok_video_15": {
        "id": "grok_video_v15",
        "use_for": "stylized/anime/high-contrast i2v from a required start image",
        "needs_start_image": True,
        "resolutions": ("480p", "720p"),
    },
}

AUDIO_MODEL = {"id": "seed_audio", "use_for": "music bed + sfx (steam, sparkle, whoosh)"}

# intent -> model id. The planner picks by intent; the provider maps id -> API.
MODEL_ROUTING: dict[str, str] = {
    "product_keyframe": "gpt_image_2",
    "cinematic_scene": "seedance_2_0",
    "premium_hero_scene": "cinema_studio_video_3_0",
    "full_ad_from_url": "marketing_studio_video",
    "budget_scene": "kling3_0",
    "music": "seed_audio",
}

# --------------------------------------------------------------------------- #
# 2. Cinematic controlled vocabulary — the words that make output look pro.
#    The planner MUST draw camera/lighting/look terms from these lists.
# --------------------------------------------------------------------------- #

CAMERA_MOVES: dict[str, str] = {
    "slow_push_in": "slow cinematic push-in, gentle parallax",
    "orbit": "smooth orbit around the product, revealing form",
    "dolly_in": "steady dolly in on a gimbal",
    "crane_up": "crane up revealing the full spread",
    "pull_back_reveal": "slow pull-back revealing product in its scene",
    "macro_detail": "extreme macro, rack focus across the surface texture",
    "whip_reveal": "fast whip-pan into a crisp hero frame (hook only)",
    "top_down_descend": "overhead top-down slowly descending",
}

LIGHTING: tuple[str, ...] = (
    "warm golden-hour window light",
    "soft rim light",
    "moody backlight with soft bokeh",
    "bright clean studio softbox",
    "dramatic single-source key light",
)

LOOK: tuple[str, ...] = (
    "photorealistic, premium commercial",
    "shallow depth of field",
    "high-end food styling",
    "editorial, crisp focus on the product",
    "subtle rising steam / falling gold dust",
)

# Universal negative guidance — video models garble text, so NEVER ask them for it.
PROMPT_GUARDRAILS = (
    "No on-screen text, no logos, no watermarks (added later by the overlay layer). "
    "Keep the product's shape, color and label faithful to the reference photo; "
    "prefer medium or angled framing over close-ups of small printed text."
)

# --------------------------------------------------------------------------- #
# 3. The 3 scene roles — each maps to a model + camera grammar + prompt shape.
# --------------------------------------------------------------------------- #

SCENE_ROLE_TEMPLATES: dict[str, dict] = {
    "hook": {
        "goal": "stop the scroll in the first second",
        "duration_s": 3,
        "keyframe_mode": "conceptual_product",
        "video_model": "seedance_2_0",
        "camera": ["whip_reveal", "slow_push_in"],
        "note": "highest-energy frame; dramatic light; product as hero",
    },
    "product": {
        "goal": "make the product look irresistible and show what it is",
        "duration_s": 5,
        "keyframe_mode": "lifestyle_scene",
        "video_model": "seedance_2_0",
        "camera": ["orbit", "macro_detail", "dolly_in"],
        "note": "appetizing detail, shallow DoF; the real product from their site",
    },
    "cta": {
        "goal": "brand + call to action; leave them wanting to buy",
        "duration_s": 4,
        "keyframe_mode": "product_shot",
        "video_model": "seedance_2_0",
        "camera": ["pull_back_reveal", "crane_up"],
        "note": "clean end frame; CTA text/logo/price are OVERLAID by HyperFrames, "
        "never generated inside the video",
    },
}

# --------------------------------------------------------------------------- #
# 4. End-to-end pipeline: customer command -> delivered cinematic reel.
# --------------------------------------------------------------------------- #

PIPELINE: list[dict] = [
    {
        "step": "ingest",
        "what": "Crawl the customer's connected store/site (or Marketing Studio "
        "import-from-URL) → real product images + brand name/palette. The agent "
        "NEVER invents the product; it grounds every scene in their actual photos.",
    },
    {
        "step": "plan",
        "what": "Planner LLM (PLANNER_SYSTEM_PROMPT) turns the brief + product into "
        "a 3-scene scene_plan JSON: per scene {role, model, camera, keyframe_prompt, "
        "video_prompt, duration}.",
    },
    {
        "step": "keyframe",
        "what": "product-photoshoot / gpt_image_2 with the REAL product photo as "
        "reference → one cinematic still per scene. Cheap; approved by the customer "
        "BEFORE any expensive video call (blueprint keyframe-first gate).",
    },
    {
        "step": "generate",
        "what": "Higgsfield seedance_2_0 image-to-video on the APPROVED keyframe + the "
        "scene's video_prompt (camera move) → cinematic clip per scene.",
    },
    {
        "step": "overlay",
        "what": "HyperFrames renders captions / logo / price / CTA end-card as a "
        "transparent layer over the clips (video models can't do clean text).",
    },
    {
        "step": "stitch",
        "what": "ffmpeg concat (probe→copy or normalize-transcode) + music bed "
        "(seed_audio) with ducking + loudnorm → final 9:16 reel bundle.",
    },
]

# --------------------------------------------------------------------------- #
# 5. Planner system prompt — the exact text the LLM receives so it TRANSLATES a
#    free-form customer command into an executable scene_plan. Fed alongside the
#    ingested product data. Output is validated against the scene_plan schema.
# --------------------------------------------------------------------------- #

PLANNER_SYSTEM_PROMPT = """\
You are the video-planning brain of Easy Life's video agent. A small-business
owner gives you a short brief (usually in Hebrew) and you already have their REAL
product data (name, description, image URLs, brand palette) crawled from their
store. Your job is to translate that into a precise, executable 3-scene plan for
a CINEMATIC, photorealistic vertical (9:16) ad — the quality bar is a modern
premium commercial, never motion-graphics over a gradient.

Rules:
- Exactly 3 scenes, in fixed order: hook, product, cta.
- Ground every scene in the customer's ACTUAL product photo (pass its image id as
  the keyframe reference). Never invent a different product.
- For each scene emit:
    role            one of: hook | product | cta
    model           the Higgsfield video model id (default "seedance_2_0")
    keyframe_prompt a photorealistic still description for the product-photoshoot
                    step — describe product, setting, lighting, framing.
    video_prompt    the MOTION the camera and subject make — draw camera terms
                    ONLY from the approved camera vocabulary; describe subject
                    motion (steam rises, gold dust falls, glaze drips).
    camera          the camera-move key(s) you used (from CAMERA_MOVES).
    duration        seconds (hook ~3, product ~5, cta ~4).
- Lighting and look terms must come from the approved LIGHTING / LOOK vocabulary.
- NEVER put on-screen text, price, logo, or a call-to-action INTO the video_prompt
  or keyframe_prompt. Those are overlaid later by the branding layer. Note the CTA
  copy separately in `overlay_text` on the cta scene.
- Keep the product's shape, color and label faithful; prefer medium/angled framing
  over close-ups of small printed text (video models garble text).

Return ONLY the scene_plan JSON.
"""


def build_scene_prompt(role: str, product_name: str, style_hint: str = "") -> dict:
    """Deterministic fallback plan for one scene when the LLM is unavailable.

    Produces a sensible keyframe + video prompt from the role template so the
    pipeline can run (and be tested) without a live LLM call. The LLM planner
    normally overrides this with a richer, product-specific plan.
    """
    tpl = SCENE_ROLE_TEMPLATES[role]
    camera_key = tpl["camera"][0]
    lighting = LIGHTING[0]
    look = ", ".join(LOOK[:3])
    keyframe = (
        f"Cinematic advertising product photograph of {product_name}, "
        f"{lighting}, {look}. {style_hint} {PROMPT_GUARDRAILS}"
    ).strip()
    video = (
        f"{CAMERA_MOVES[camera_key]}, {lighting}, {look}. {PROMPT_GUARDRAILS}"
    )
    return {
        "role": role,
        "model": tpl["video_model"],
        "camera": [camera_key],
        "keyframe_prompt": keyframe,
        "video_prompt": video,
        "duration": tpl["duration_s"],
        **({"overlay_text": None} if role == "cta" else {}),
    }


def default_plan(product_name: str, style_hint: str = "") -> list[dict]:
    """A full 3-scene deterministic plan — the no-LLM fallback and the test fixture."""
    return [build_scene_prompt(role, product_name, style_hint) for role in ("hook", "product", "cta")]
